#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@google-auth[-1]
	add ucitrack google-auth
	set ucitrack.@google-auth[-1].init=google-auth
	commit ucitrack
EOF


rm -f /tmp/luci-indexcache
exit 0
